# Relative to root directory
siteconfig:
  deployFolder: 'deploy'
  deployRoot: '../shinydemos-misc'
  demosFolder: 'demos'
  sourceFolder: 'source'
  layoutsFolder: 'layouts'

# Allowed tags: css3, svg, multimedia, webgl, canvas, device, getusermedia
# We'll probably add a "belowDemos" field for copy to highlight dev.opera articles in the future.
# Right now there's no visual support for that, but copy has been written.

tags:
  - tagName: css3
    displayName: 'CSS 3'
    tagline: 'CSS 3: CSS was co-invented by Opera&rsquo;s CTO, Håkon Wium Lie, so that Web pages could have beautiful designs. It started life as a method of specifying fonts and colours, and now provides simple animations, entire layouts and is the underpinning of Responsive Web Design.'

  - tagName: svg
    displayName: 'SVG'
    tagline: 'You want scriptable text and images, that can be manipulated using their own DOM, CSS and script, in all modern browsers? You want to produce graphics that look sharp at phone screen size or widescreen TV size? And you want to be able to make them responsive too? Of course you do &mdash; so meet SVG: Scalable Vector Graphics. But you&rsquo;ll say “Shiny! Very Groovy”. And you&rsquo;d be right.'

  - tagName: audio-video
    displayName: 'Audio & Video'
    tagline: 'For years, the only way to add audio or video to web pages was with a plugin. Totally lame, daddy-o! These days, media can be embedded straight in the page with the HTML5 <code>&lt;audio&gt;</code> and <code>&lt;video&gt;</code> elements then decoded &mdash; and video manipulated &mdash; natively in the browser.'

  - tagName: webgl
    displayName: 'WebGL'
    tagline: 'WebGL brings OpenGL, the language of games developers, to the Web. Providing 3D graphics and low-level access down to the graphics card, it&rsquo;s hard to learn but incredibly powerful for graphics and visualizations. The gaming experience is coming to the Web, and plugins can just plug off.<br><br>In Opera 12 desktop, enable webGL by entering <a href="opera:config#UserPrefs|EnableWebGL">Enable WebGL in opera:config</a> by setting the value to 1, and <a href="opera:config#UserPrefs|EnableHardwareAcceleration">Enable Hardware Acceleration</a> similarly.'

  - tagName: canvas
    displayName: 'Canvas'
    tagline: 'Who said images had to be static? Boring people, that&rsquo;s who. Until <code>&lt;canvas&gt;</code> was available, you had to move things around the screen using DHTML &mdash; which stands for “Damned Hard To Make, Let&rsquo;sCopyFromSomeWebsite”. Now you can push pixels straight to the screen with JavaScript. It&rsquo;s not only for first person shooters: by copying from videos or <code>getUserMedia</code> we produce image and video modification tools. Right now, in all modern browsers.'

  - tagName: touch
    displayName: 'Touch'
    tagline: 'Browsers are integrating with native device capabilities to make Web apps ever-closer to native apps. For example, touch input is natural and intuitive, and it&rsquo;s revolutionised handheld devices. It&rsquo;s time to get Peter Pointer and Ruby Ring off the mouse and onto the screen. Make sure your designs have big fat hit areas. And colours that shine through grease.'

  - tagName: getusermedia
    displayName: 'getUserMedia'
    tagline: '<code>getUserMedia</code> is an API that began as part of HTML5 and was split off into the W3C WebRTC specification suite. It allows JavaScript access to a device&rsquo;s cameras and microphones. Think in-browser video-conferencing! Think augmented reality! Think Shiny! Use Opera 12, Opera Mobile 12 or Chrome Canary to see the demos.'

# List of all active demos with description
demos:
  - slug: 3d-color-histogram
    title: '3D Color Histogram'
    legend: 'Visualize frame by frame color decomposition. Choose from different <a href="http://en.wikipedia.org/wiki/HSL_and_HSV">color schemes</a> below. Feel free to pause the video and to zoom/pan the histogram below.'
    tags: [webgl, getusermedia]
    support: [canvas, getusermedia, video, webgl, webworkers]

  - slug: beach
    title: 'Beach'
    legend: 'Wake up to the sound of waves breaking on shore. Press the button to open up your CSS gradient blinds, and see your room transition from dark to light. The beach is deserted, so why not try {swimsuit: none} ?'
    tags: [css3]
    support: [csstransitions, cssgradients]

  - slug: border-salon
    title: 'Border Radius Salon'
    legend: 'If you&rsquo;ve tried the border-fun demo, you&rsquo;ve made some borders so gorgeous they should be in a gallery. border-salon is a gallery of rounded-corner loveliness &mdash; all randomly generated for your delight!'
    tags: [css3]
    support: [borderradius, borderimage]

  - slug: border-radius-fun
    title: 'Tinkering with Border Radius'
    legend: 'There&rsquo;s no corner like a rounded corner, said Shakespeare. This demo allows you to try before you buy; use the HTML5 sliders to change your radii in real time, then save the code.'
    tags: [css3]
    support: [borderradius]

  - slug: clock
    title: 'A Time of Reflection'
    legend: 'Tick, tock, tick, tock. Stare into your webcam. Marvel at the World&rsquo;s best-looking clock face.'
    tags: [css3, getusermedia, svg]
    support: [getusermedia]

  - slug: color-picker
    title: 'Real Life Color Picker'
    legend: 'getUserMedia isn&rsquo;t just about taking photos. By copying the data into canvas, you can perform image analysis. This demo contructs a pallete of the dominant colours in the image.'
    tags: [css3, getusermedia]
    support: [getusermedia]

  - slug: cracked
    title: 'Cracked'
    legend: 'In case of emergency, break glass!'
    tags: [getusermedia]
    support: [getusermedia, canvas, video]

  - slug: emberwind
    title: 'Emberwind'
    legend: 'Help free the city of Grendale from the evil CandleFinger and his gremlin hordes. The grand city of Grendale is under siege by mischievous hordes of gremlins. Emberwind is a 2D platform game, re-written to use Open Web technologies.'
    tags: [webgl, canvas]
    support: [webgl, canvas, audio]

  - slug: explode
    title: 'Explode'
    legend: 'Blow up the video, and watch as the shards still continue to move. Based on Sean Christmann&rsquo;s <a href="http://www.craftymind.com/2010/04/20/blowing-up-html5-video-and-mapping-it-into-3d-space/">exploding HTML5 video experiment</a> with kind permission.'
    tags: [getusermedia]
    support: [getusermedia, canvas, video]

  - slug: facekat
    title: 'FaceKat'
    legend: 'First there were punched cards for computer input, then the keyboard, the mouse, mouse gestures, the touchscreen &mdash; and now the head-wiggle! Avoid the obstacles by steering &mdash; with your head. It&rsquo;s not quite <a href="http://dev.opera.com/articles/view/labs-introducing-opera-face-gestures/">face gestures</a> &mdash; yet.'
    tags: [getusermedia]
    support: [getusermedia, video]

#  - slug: fence
#    title: 'Fence'
#    legend: 'Resize the browser window (or click on “danger area”). Notice how you never see half square of chicken wire fence; the browser always ensures you see full squares only. If we say that CSS kicks ass, please don&rsquo;t take offence.'
#    tags: [css3, svg]
#    support: [svg, inlinesvg, bgrepeatround]

  - slug: hixie-keyboard
    title: 'Hixie Keyboard'
    legend: 'Press any key to make Hixie, the HTML5 editor, speak. Originally an HTML5 homage to <a href="http://www2.b3ta.com/buffyswear/">Buffy&rsquo;s Swearing Keyboard</a> (NSFW, due to bad language and Flash).'
    tags: [audio-video, css3]
    support: [audio, video]

  - slug: inbox-attack
    title: 'Inbox Attack'
    legend: 'The 1980s meets 2012. Can you deal with the ever-quickening deluge of emails and keep inbox zero?'
    tags: [svg]
    support: [svg]

  - slug: odin
    title: 'ODIN'
    legend: 'Opera is the only European browser, proudly based in Norway, where in the long dark winter, trolls roam free, mucking up your Git history by committing without useful commit messages. Every coder needs Odin to protect them, so here he is &mdash; through the magic of WebGL.'
    tags: [webgl]
    support: [webgl, audio]

  - slug: paranoid
    title: 'Return of the Retro with a canvas game!'
    legend: 'DIMENSION-CONTROLLING FORT “DOH” HAS NOW BEEN DEMOLISHED, AND TIME STARTED FLOWING REVERSELY. And when time flows reversely, retro games get remade with HTML5.'
    tags: [canvas]
    support: [canvas]

  - slug: photo-booth
    title: 'Photobooth in Your browser'
    legend: 'Free online photo booth! Use getUserMedia for taking the shots, then email them to yourself. They are suitable for passports to travel anywhere on the World Wide Web.'
    tags: [canvas, getusermedia]
    support: [getusermedia, video, canvas]

  - slug: picture-organizer
    title: 'Picture Organiser'
    legend: 'Organising pictures is a drag. Use your touch screen to rotate or drag the pictures around with your finger. This demo combines touch events and CSS transforms and multiple background images.'
    tags: [css3, touch]
    support: [touch]

  - slug: qr-code
    title: 'QRY {curie} QR code reader'
    legend: 'Use a QR code as input for a website: getUserMedia grabs the image which is the processed using <a href="https://github.com/LazarSoft/jsqrcode">LazarSoft&rsquo;s jsQRcode implementation</a>. Who knows? You might find yourself featured on <a href="http://picturesofpeoplescanningqrcodes.tumblr.com/">picturesofpeoplescanningqrcodes.tumblr.com</a>.'
    tags: [getusermedia]
    support: [getusermedia, video]

  - slug: rock-piano
    title: 'Rock Piano'
    legend: 'This Shiny rock piano combines Touch events, classList, HTML5 audio, border-radius, box-shadow, and gradients. Soon, all your friends, neighbours and that cutie from Accounts will call you “HTM-Elton John”.'
    tags: [css3, audio-video]
    support: [audio]

  - slug: tatami
    title: 'Tatami'
    legend: 'A tatami is a type of mat used as a flooring material in traditional Japanese-style rooms. There are rules concerning auspicious layouts of tatami. In homes, the mats must not be laid in a grid pattern, and in any layout there is never a point where the corners of four mats touch.'
    tags: [css3]
    support: [csstransitions]

  - slug: touch-tracker
    title: 'Touch Tracker'
    legend: 'Using the magic of multitouch, you can see what robots&rsquo; fingerprints would look like.'
    tags: [canvas, touch]
    support: [canvas, touch]

  - slug: warholiser
    title: 'Warholiser'
    legend: 'Now you can make a Warhol picture with no need for skill or talent, in no time at all. Just like he did.'
    tags: [canvas, getusermedia]
    support: [canvas, getusermedia, video]

  - slug: world-flights
    title: 'World Flights'
    legend: 'Visualize the major airline routes. Feel free to pan and zoom the Earth.'
    tags: [webgl]
    support: [canvas, webgl, webworkers]

  - slug: hipster-dog
    title: 'Hipster Dog'
    legend: 'Was it not Wordsworth who said "Earth hath nothing to show more fair / than a hipster dog riding a penny-farthing and bumping into giant shoes"? Tragically, he died without ever seeing Opera 12 move out of beta. In her moving tribute to Wordsworth, Luz has recreated this most elegiac of English poems, using CSS Animations and HTML5 audio instead of metaphor and synecdoche. Music by the incomparable <a href="http://incompetech.com/m/c/royalty-free/index.html?keywords=pixel">Kevin MacLeod</a>'
    tags: [css3, audio-video]
    support: [csstransitions, cssanimations, audio]

# Supported features list. Based on custom Modernizr build
features:
  - slug: applicationcache
    title: 'App Cache'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/offline.html'

  - slug: audio
    title: 'HTML Audio'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#audio'

  - slug: backgroundsize
    title: 'CSS background-size'
    link: 'http://www.w3.org/TR/css3-background/#the-background-size'

  - slug: bgrepeatround
    title: 'CSS background-repeat: round'
    link: 'http://www.w3.org/TR/css3-background/#background-repeat'

  - slug: bgrepeatspace
    title: 'CSS background-repeat: space'
    link: 'http://www.w3.org/TR/css3-background/#background-repeat'

  - slug: bgrepeatspace
    title: 'CSS background-repeat: space'
    link: 'http://www.w3.org/TR/css3-background/#background-repeat'

  - slug: borderimage
    title: 'CSS border-image'
    link: 'http://www.w3.org/TR/css3-background/#the-border-image'

  - slug: borderradius
    title: 'CSS border-radius'
    link: 'http://www.w3.org/TR/css3-background/#the-border-radius'

  - slug: boxshadow
    title: 'CSS box-shadow'
    link: 'http://www.w3.org/TR/css3-background/#box-shadow'

  - slug: canvas
    title: 'Canvas'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#the-canvas-element'

  - slug: canvastext
    title: 'Canvas Text'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#drawing-text-to-the-canvas'

  - slug: cssanimations
    title: 'CSS Animations'
    link: 'http://www.w3.org/TR/css3-animations/'

  - slug: csscolumns
    title: 'CSS Multi-column'
    link: 'http://www.w3.org/TR/css3-multicol/'

  - slug: cssgradients
    title: 'CSS Gradients'
    link: 'http://www.w3.org/TR/css3-images/#gradients'

  - slug: csstransforms
    title: 'CSS 2D Transforms'
    link: 'http://www.w3.org/TR/css3-2d-transforms/'

  - slug: csstransforms3d
    title: 'CSS 3D Trnasforms'
    link: 'http://www.w3.org/TR/css3-3d-transforms/'

  - slug: csstransitions
    title: 'CSS Transitions'
    link: 'http://www.w3.org/TR/css3-transitions/'

  - slug: draganddrop
    title: 'HTML Drag and Drop'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html#dnd'

  - slug: flexbox
    title: 'CSS Flexbox'
    link: 'http://www.w3.org/TR/css3-flexbox/'

  - slug: fontface
    title: 'CSS Web Fonts'
    link: 'http://www.w3.org/TR/css3-webfonts/'

  - slug: generatedcontent
    title: 'CSS Generated Content'
    link: 'http://www.w3.org/TR/CSS21/generate.html'

  - slug: geolocation
    title: 'Geolocation API'
    link: 'http://www.w3.org/TR/geolocation-API/'

  - slug: getusermedia
    title: 'WebRTC getUserMedia'
    link: 'http://www.w3.org/TR/webrtc/'

  - slug: hashchange
    title: 'HTML hashChange event'
    link: 'http://www.w3.org/TR/html5/history.html#event-hashchange'

  - slug: history
    title: 'HTML History and Location API'
    link: 'http://www.w3.org/TR/html5/history.html'

  - slug: hsla
    title: 'CSS HSLA colors'
    link: 'http://www.w3.org/TR/css3-color/#hsla-color'

  - slug: indexeddb
    title: 'Indexed Database API'
    link: 'http://www.w3.org/TR/IndexedDB/'

  - slug: inlinesvg
    title: 'Inline SVG'
    link: 'http://dev.w3.org/html5/spec/svg-0.html'

  - slug: js
    title: 'JavaScript'
    link: 'http://ecma-international.org/ecma-262/5.1/'

  - slug: localstorage
    title: 'Web Storage localStorage'
    link: 'http://www.w3.org/TR/webstorage/#the-localstorage-attribute'

  - slug: multiplebgs
    title: 'CSS Multiple Backgrounds'
    link: 'http://www.w3.org/TR/css3-background/#layering'

  - slug: opacity
    title: 'CSS opacity'
    link: 'http://www.w3.org/TR/css3-color/#transparency'

  - slug: pagedcontent
    title: 'CSS Generated Content for Paged Media'
    link: 'http://dev.w3.org/csswg/css3-gcpm/'

  - slug: postmessage
    title: 'HTML postMessage'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/web-messaging.html#crossDocumentMessages'

  - slug: rgba
    title: 'CSS RGBA colors'
    link: 'http://www.w3.org/TR/css3-color/#rgba-color'

  - slug: sessionstorage
    title: 'Web Storage sessionStorage'
    link: 'http://www.w3.org/TR/webstorage/#the-sessionstorage-attribute'

  - slug: smil
    title: 'SVG SMIL animation'
    link: 'http://www.w3.org/TR/SVG/animate.html'

  - slug: svg
    title: 'SVG'
    link: 'http://www.w3.org/TR/SVG/'

  - slug: textshadow
    title: 'CSS text-shadow'
    link: 'http://www.w3.org/TR/css3-text/#text-shadow'

  - slug: touch
    title: 'Touch Events'
    link: 'http://www.w3.org/TR/touch-events/'

  - slug: video
    title: 'HTML Video'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#video'

  - slug: webgl
    title: 'WebGL'
    link: 'https://www.khronos.org/registry/webgl/specs/1.0/'

  - slug: websockets
    title: 'WebSocket API'
    link: 'http://www.w3.org/TR/websockets/'

  - slug: webworkers
    title: 'Web Workers'
    link: 'http://www.whatwg.org/specs/web-apps/current-work/multipage/workers.html'
