
# Relative to root directory
siteconfig:
  deployFolder: 'deploy'
  demosFolder: 'demos'
  sourceFolder: 'source'
  layoutsFolder: 'layouts'
  panelCSS: 'panel.css'
  panelJS: 'modernizr.js'
  panelClass: 'sd-panel'
  panelTag: 'div'


# Allowed tags: javascript, forms, canvas, content, parser, svg, css, audio, video, webgl
demos:
  - slug: inbox-attack
    title: "Inbox Attack"
    tags: [svg]
    support: [svg]

  - slug: slideshows 
    title: "Slides from Web Openers"
    tags: [css]
    support: [pagedcontent]

  - slug: border-salon
    title: "Border Radius Salon"
    tags: [css]
    support: []

  - slug: photo-booth
    title: "Photobooth in Your browser"
    tags: [javascript, canvas]
    support: [getusermedia, video]

  - slug: planetarium
    title: "HTML5 Planetarium"
    tags: [css]
    support: [csstransforms, csstransitions]

  - slug: hixie-keyboard
    title: "Hixie Keyboard"
    tags: [audio, video, css]
    support: [audio, video]

  - slug: fence
    title: "Fence"
    tags: [css, svg]
    support: []

  - slug: paranoid
    title: "Return of the Retro with a canvas game!"
    tags: [canvas]
    support: [canvas]

  - slug: object-fitness
    title: "Object Fit"
    tags: [css]
    support: [object-fit]

  - slug: rock-piano
    title: "Rock Piano"
    tags: [css, audio]
    support: [audio]

  - slug: tatami
    title: "Tatami"
    tags: [css]
    support: [csstransitions]

  - slug: isometric-city
    title: "An isometric world"
    tags: [css]
    support: [csstransitions]

  - slug: border-radius-fun
    title: "Tinkering with Border Radius"
    tags: [css]
    support: []

  - slug: tweetmap
    title: "A map of tweets from the public timeline"
    tags: [svg]
    support: [svg]

  - slug: 3d-color-histogram
    title: "3D color histogram"
    tags: [webgl]
    support: [canvas, video, webgl, webworkers]

  - slug: QRY
    title: "QRY {curie} QR code reader"
    tags: [getusermedia]
    support: [getusermedia, video]

  - slug: world-flights
    title: "World flights"
    tags: [webgl]
    support: [canvas, webgl, webworkers]
